import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "./Component/Layout/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FitStick",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} bg-[#08101c]`}>
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  );
}
